name: Build Custom APK
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-apk:
    name: Compile Custom Android APK
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.2'

      - name: Checkout mobile code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: flutter pub get

      - name: Code generation
        run: dart run build_runner build

      - name: Build release APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lichess-custom-bases-apk
          path: build/app/outputs/flutter-apk/app-release.apk
